#! /bin/bash

# Flag for deb non-interactive installation to avoid any pop-ups
export UCF_FORCE_CONFFOLD=1
export DEBIAN_FRONTEND=noninteractive

# Identify & validate the OS
OS_TYPE=$(source /etc/os-release; echo $ID_LIKE);
OS_NAME=$(source /etc/os-release; echo $ID);
OS_VERSION=$(source /etc/os-release; echo $VERSION_ID);

# Generate random password for db root and jwtplus db user
DB_NAME=jwtplus_$(tr -dc 'a-z0-9' < /dev/urandom | head -c 6);
DB_USER=jwtplususer_$(tr -dc 'a-z0-9' < /dev/urandom | head -c 6);
DB_PASS_ROOT=$(tr -dc 'A-Za-z0-9!@#$^&*-' < /dev/urandom | head -c 15);
DB_PASS_USER=$(tr -dc 'A-Za-z0-9!@#$^&*-' < /dev/urandom | head -c 13);

BINARY_NAME=jwtplus
BINARY_REMOTE=https://github.com/jwtplus/jwtplus/releases/latest/download/jwtplus-linux-amd64.tar.gz
INSTALL_FOLDER=/opt/jwtplus/
BINARY_INSTALL=$INSTALL_FOLDER$BINARY_NAME
IP_ADDRESS=0.0.0.0
APP_PORT=2025
CONFIG_FILE="jwtplus.yaml"

SYSTEMD_FILE=/etc/systemd/system/$BINARY_NAME.service

cat << EOF
-------------------------------------------------
Linux Type: $OS_TYPE
Distro Name: $OS_NAME
Version: $OS_VERSION
-------------------------------------------------
EOF

# Set the Server Timezone to UTC
timedatectl set-timezone UTC

# Update the installed packages
echo "Updating system";
apt-get update; apt-get -y upgrade; apt-get -y autoremove; apt-get -y autoclean;

# Install firewall & common network tools
echo "Installing firewall";
apt-get install -y ufw net-tools;

# Enable firewalls and allow enable common ports
echo "Starting firewall"
ufw --force enable;
ufw allow 22;
ufw allow 80;
ufw allow 443;
ufw allow $APP_PORT;

# install MariaDB database server along with important packages
echo "Installing database";
apt-get install -y mariadb-server wget;
systemctl enable mariadb;
systemctl restart mariadb;

# Mysql Secure installation
echo "Securing database"
mariadb -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')";
mariadb -u root -e "DELETE FROM mysql.user WHERE User=''";
mariadb -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'";

# Set the db root password
mariadb -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_PASS_ROOT')";

# Create new database and user for password software
mariadb -u root -e "CREATE DATABASE $DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci";
mariadb -u root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS_USER'";
mariadb -u root -e "CREATE USER '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASS_USER'";
mariadb -u root -e "CREATE USER '$DB_USER'@'::1' IDENTIFIED BY '$DB_PASS_USER'";
mariadb -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'";
mariadb -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'127.0.0.1'";
mariadb -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'::1'";

# Flush priviles and make it effective
mariadb -u root -e "FLUSH PRIVILEGES";

# Write db credentials in the file for the later usage
echo "Writing database credentials in /root/database.txt";
cat >> /root/database.txt <<EOF
------------------------------------------------
Generated by JWTPlus installation script
------------------------------------------------
Database Location: localhost
Database Port: 3306
Database Username: $DB_USER
Database Password: $DB_PASS_USER
Database Name: $DB_NAME
------------------------------------------------
Database Root Password: $DB_PASS_ROOT
------------------------------------------------
EOF

# Download & Install
echo "Downloading & installing JWTPlus binary"
mkdir -p $INSTALL_FOLDER
cd $INSTALL_FOLDER
wget -O jwtplus.tar.gz $BINARY_REMOTE;
tar -xzf jwtplus.tar.gz
mv jwtplus-linux-amd64/jwtplus-linux-amd64 ./jwtplus;
chmod +x jwtplus
rm -r jwtplus-linux-amd64/;
rm jwtplus.tar.gz;

echo "Generating JWTPlus configuration file..."
cat <<EOF > "$CONFIG_FILE"
debug: false
server:
  ip: $IP_ADDRESS
  port: $APP_PORT
db:
  location: 127.0.0.1
  port: 3306
  username: $DB_USER
  password: $DB_PASS_USER
  dbname: $DB_NAME
EOF

# Display generated config
echo "Configuration file generated successfully: $CONFIG_FILE"
cat "$CONFIG_FILE"

echo "Loading database table and creating root key";
/opt/jwtplus/jwtplus install >> /root/root-key.txt

# Create Service file for Systemd
cat >> $SYSTEMD_FILE <<EOF
[Unit]
Description=JWTPlus
After=network.target mysql.service

[Service]
Type=simple
ExecStart=$BINARY_INSTALL run
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=jwtplus
User=root
Group=root
WorkingDirectory=/opt/jwtplus

[Install]
WantedBy=multi-user.target
EOF

# Start & enable jwtplus as service 
systemctl enable jwtplus;
systemctl start jwtplus;
clear;

# Installation Completed, Printout the important details
cat << EOF
-------------------------------------------------
Installation Completed

1. Your root key can be received from /root/root-key.txt file
2. Your database root password can be retrieved from /root/database.txt file

JWTPlus Service Commands
To start:- service jwtplus start
To restart:- service jwtplus restart
To stop:- service jwtplus stop

-------------------------------------------------
EOF