#! /bin/bash

# Identify & validate the OS
OS_TYPE=$(source /etc/os-release; echo $ID_LIKE);
OS_NAME=$(source /etc/os-release; echo $ID);
OS_VERSION=$(source /etc/os-release; echo $VERSION_ID);

# Generate random passwords for db root and jwtplus db user
DB_NAME=jwtplus_$(tr -dc 'a-z0-9' < /dev/urandom | head -c 6);
DB_USER=jwtplususer_$(tr -dc 'a-z0-9' < /dev/urandom | head -c 6);
DB_PASS_ROOT=$(tr -dc 'A-Za-z0-9!@#$^&*-' < /dev/urandom | head -c 15);
DB_PASS_USER=$(tr -dc 'A-Za-z0-9!@#$^&*-' < /dev/urandom | head -c 13);

BINARY_NAME=jwtplus
BINARY_REMOTE=https://github.com/jwtplus/jwtplus/releases/latest/download/jwtplus-linux-amd64.tar.gz
INSTALL_FOLDER=/opt/jwtplus/
BINARY_INSTALL=$INSTALL_FOLDER$BINARY_NAME
IP_ADDRESS=0.0.0.0
APP_PORT=2025
CONFIG_FILE="jwtplus.yaml"
SYSTEMD_FILE=/etc/systemd/system/$BINARY_NAME.service

cat << EOF
-------------------------------------------------
Linux Type: $OS_TYPE
Distro Name: $OS_NAME
Version: $OS_VERSION
-------------------------------------------------
EOF

# Set the Server Timezone to UTC
timedatectl set-timezone UTC

# Update the installed packages
echo "Updating system";
yum -y update || dnf -y update;

# Install firewall & common network tools
echo "Installing firewall";
yum install -y firewalld net-tools || dnf install -y firewalld net-tools;

# Enable firewall and allow common ports
echo "Starting firewall"
systemctl enable firewalld;
systemctl start firewalld;
firewall-cmd --permanent --add-service=ssh;
firewall-cmd --permanent --add-service=http;
firewall-cmd --permanent --add-service=https;
firewall-cmd --permanent --add-port=$APP_PORT/tcp;
firewall-cmd --reload;

# Install MariaDB database server
echo "Installing database";
yum install -y mariadb-server wget || dnf install -y mariadb-server wget;
systemctl enable mariadb;
systemctl restart mariadb;

# Secure MySQL installation
echo "Securing database";
mariadb -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')";
mariadb -u root -e "DELETE FROM mysql.user WHERE User=''";
mariadb -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'";

# Set the db root password
mariadb -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_PASS_ROOT')";

# Create new database and user for JWTPlus
mariadb -u root -e "CREATE DATABASE $DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci";
mariadb -u root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS_USER'";
mariadb -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'";
mariadb -u root -e "FLUSH PRIVILEGES";

# Save database credentials
echo "Writing database credentials in /root/database.txt";
cat >> /root/database.txt <<EOF
------------------------------------------------
Generated by JWTPlus installation script
------------------------------------------------
Database Location: localhost
Database Port: 3306
Database Username: $DB_USER
Database Password: $DB_PASS_USER
Database Name: $DB_NAME
------------------------------------------------
Database Root Password: $DB_PASS_ROOT
------------------------------------------------
EOF

# Download & Install JWTPlus
echo "Downloading & installing JWTPlus binary";
mkdir -p $INSTALL_FOLDER;
cd $INSTALL_FOLDER;
wget -O jwtplus.tar.gz $BINARY_REMOTE;
tar -xzf jwtplus.tar.gz;
mv jwtplus-linux-amd64/jwtplus-linux-amd64 ./jwtplus;
chmod +x jwtplus;
rm -r jwtplus-linux-amd64/;
rm jwtplus.tar.gz;

# Generate configuration file
echo "Generating JWTPlus configuration file...";
cat <<EOF > "$CONFIG_FILE"
debug: false
server:
  ip: $IP_ADDRESS
  port: $APP_PORT
db:
  location: 127.0.0.1
  port: 3306
  username: $DB_USER
  password: $DB_PASS_USER
  dbname: $DB_NAME
EOF

# Display config
echo "Configuration file generated successfully: $CONFIG_FILE";
cat "$CONFIG_FILE";

# Load database table and create root key
echo "Loading database table and creating root key";
/opt/jwtplus/jwtplus install >> /root/root-key.txt;

# Create Systemd service file
cat > $SYSTEMD_FILE <<EOF
[Unit]
Description=JWTPlus
After=network.target mariadb.service

[Service]
Type=simple
ExecStart=$BINARY_INSTALL run
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=jwtplus
User=root
Group=root
WorkingDirectory=/opt/jwtplus

[Install]
WantedBy=multi-user.target
EOF

# Enable & start JWTPlus service
systemctl enable jwtplus;
systemctl start jwtplus;

# Installation Completed, Printout the important details
cat << EOF
-------------------------------------------------
Installation Completed

1. Your root key can be received from /root/root-key.txt file
2. Your database root password can be retrieved from /root/database.txt file

JWTPlus Service Commands
To start:- service jwtplus start
To restart:- service jwtplus restart
To stop:- service jwtplus stop

-------------------------------------------------
EOF
